baseurl = "http://www.example.com"
title = "Davide Murari"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

#disqusShortname = "davide"

[markup.highlight]
style = "github-dark"

[params]
  author = "Davide Murari"
  info = "Postdoctoral Research Associate at the University of Cambridge\n\n Working on the connections between dynamical systems and neural networks"
  description = "Davide Murari's personal website"
  keywords = "davide murari, neural odes, geometric numerical integration, dynamical systems and neural networks"
  avatarurl = "images/profile.png"
  since = 2019
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-GD5GGFV8ZQ"

# Social links
[[params.social]]
  name = "ResearchGate"
  icon = "fa fa-researchgate fa-2x"
  weight = 1
  url = "https://www.researchgate.net/profile/Davide-Murari/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/davidemurari/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/dademurari/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about"
[[menu.main]]
  name = "Academic publications"
  weight = 3
  url = "publications"
[[menu.main]]
  name = "Academic talks"
  weight = 4
  url = "talks"
[[menu.main]]
  name = "Teaching"
  weight = 5
  url = "teaching"
[[menu.main]]
  name = "CV"
  weight = 6
  url = "cv.pdf"